{
 "title": "piMeter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Verbrauch Gesamt",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "kwatth",
   "valueName": "current",
   "targets": [
    {
     "alias": "1",
     "measurement": "energy",
     "query": "SELECT sum(\"WirkenergieL1\")  / 1000 + sum(\"WirkenergieL2\") / 1000 + sum(\"WirkenergieL3\") / 1000 FROM \"energy\"",
     "select": [
      [
       { "params": [ "WirkenergieL1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kosten",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "format": "currencyEUR",
   "valueName": "current",
   "targets": [
    {
     "alias": "1",
     "measurement": "energy",
     "query": "SELECT (sum(\"WirkenergieL1\")  / 1000 + sum(\"WirkenergieL2\") / 1000 + sum(\"WirkenergieL3\") / 1000) * 0.27 FROM \"energy\"",
     "select": [
      [
       { "params": [ "WirkenergieL1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbrauch / h",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "WirkenergieL1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "WirkenergieL2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "L3",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "WirkenergieL3" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Verbrauch / Tag",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "WirkenergieL1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "WirkenergieL2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "L3",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "WirkenergieL3" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dieses Jahr",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "alias": "L1",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "WirkenergieL1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "L2",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "WirkenergieL2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "L3",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "WirkenergieL3" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Strom",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    {
     "alias": "Strom L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "StromL1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Strom L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "StromL2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Strom L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "StromL3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spannung",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "Spannung L1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "SpannungL1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Spannung L2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "SpannungL2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Spannung L3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "energy",
     "select": [
      [
       { "params": [ "SpannungL3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}